#!/usr/bin/env bash
#
# ASE Docker Entry Point
# Initializes and starts SAP ASE server
#

set -eo pipefail
source ./SYBASE.sh
set -u

# SQL initialization directory
SQL_DIR="${SQL_DIR:-/docker-entrypoint-initdb.d}"

# ASE connection configuration
ASE_HOST="${ASE_HOST:-localhost}"
ASE_PORT="${ASE_PORT:-5000}"
ASE_DB="${ASE_DB:-master}"

# Data source name for interfaces file
export ASE_DS_NAME=${ASE_DS_NAME:-MYSYBASE}

# SA password - generate random if not provided
export ASE_SA_PASSWORD=${ASE_SA_PASSWORD:-$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 16; echo)}

# Installation and data paths
export ASE_INSTALL_PATH=$SYBASE
export ASE_DATA_PATH=${ASE_DATA_PATH:-${ASE_INSTALL_PATH}/data}

# Character set, language, and sort order configuration
ASE_CHARSET="${ASE_CHARSET:-utf8}"
ASE_LANGUAGE="${ASE_LANGUAGE:-us_english}"
ASE_SORT_ORDER="${ASE_SORT_ORDER:-binary}"

if [ "${ASE_LANGUAGE}" = "us_english" ]; then
    ASE_LANGUAGE_INSTALL_LIST="us_english"
else
    ASE_LANGUAGE_INSTALL_LIST="us_english,${ASE_LANGUAGE}"
fi

# Maximum time to wait for ASE startup (seconds)
WAIT_SEC="${WAIT_SEC:-60}"

# Logging functions
log_info() {
    echo "[INFO] $*"
}

log_error() {
    echo "[ERROR] $*" >&2
}

# Execute isql command with error handling
isql_cmd() {
    # --retserverror: Return server error codes
    # -b: Exit on error (batch mode)
    # -w: Output width
    isql --retserverror -S "${ASE_DS_NAME}" -Usa -P "${ASE_SA_PASSWORD}" -D "${ASE_DB}" -w 1000 "$@"
}

# Wait for ASE server to be ready
wait_for_ase() {
    local max_wait="${1:-60}"
    local elapsed=0
    local interval=5

    log_info "Waiting for ASE server to be ready (max ${max_wait}s)..."

    while [ ${elapsed} -lt ${max_wait} ]; do
        if isql -S "${ASE_DS_NAME}" -Usa -P "${ASE_SA_PASSWORD}" -D "${ASE_DB}" <<-SQL 2>/dev/null
SELECT 1
GO
SQL
        then
            log_info "ASE server is ready and accepting connections"
            return 0
        fi

        log_info "Waiting for ASE... (${elapsed}s/${max_wait}s)"
        sleep ${interval}
        elapsed=$((elapsed + interval))
    done

    log_error "ASE server did not become ready within ${max_wait}s"
    return 1
}

process_init_files() {
    local init_dir="${SQL_DIR}"
    if [ ! -d "${init_dir}" ]; then
        return 0
    fi


    local files
    files=$(find "${init_dir}" -maxdepth 1 -type f \( -name "*.sql" -o -name "*.sh" \) 2>/dev/null | sort)
    if [ -z "${files}" ]; then
        return 0
    fi

    local count
    count=$(echo "${files}" | wc -l)
    log_info "Processing ${count} initialization file(s) from ${init_dir}..."

    echo "${files}" | while IFS= read -r f; do
        case "$f" in
            *.sh)
                if [ -x "$f" ]; then
                    log_info "Running $f"
                    "$f"
                else
                    log_info "Sourcing $f"
                    . "$f"
                fi
                ;;
            *.sql)
                log_info "Running $f"
                if ! isql_cmd < "$f"; then
                    log_error "Failed to execute $f"
                    exit 1
                fi
                ;;
        esac
    done
}

# Ensure required directories and files exist
mkdir -p "${ASE_DATA_PATH}"
touch "${SYBASE}/interfaces"

# Check if ASE is already configured
RUN_FILE="${SYBASE}/${SYBASE_ASE}/install/RUN_${ASE_DS_NAME}"

if [[ ! -f "${RUN_FILE}" ]]; then
    log_info "ASE not configured, performing initial setup..."

    # Security: Set restrictive umask for temp files
    umask 077
    SQLBUILD_RES="$(mktemp /tmp/sap-sqlbuild-res.XXXXXX)"
    trap 'rm -f "${SQLBUILD_RES}" "${SQLLOC_RES:-}"' EXIT

    # Generate srvbuildres resource file
    cat <<EOF > "${SQLBUILD_RES}"
# --- This file was generated by Sybase Installer ---
#
sybinit.release_directory: ${ASE_INSTALL_PATH}
sybinit.product: sqlsrv
sqlsrv.server_name: ${ASE_DS_NAME}
sqlsrv.sa_password: ${ASE_SA_PASSWORD}
sqlsrv.new_config: yes
sqlsrv.do_add_server: yes
sqlsrv.network_protocol_list: tcp
sqlsrv.network_hostname_list: localhost
sqlsrv.network_port_list: ${ASE_PORT}
sqlsrv.application_type: MIXED
sqlsrv.server_page_size: 16k
sqlsrv.force_buildmaster: no
sqlsrv.addl_cmdline_parameters:
sqlsrv.master_device_physical_name: ${ASE_DATA_PATH}/master.dat
sqlsrv.master_device_size: 384
sqlsrv.master_database_size: 300
sqlsrv.errorlog: ${ASE_INSTALL_PATH}/${SYBASE_ASE}/install/${ASE_DS_NAME}.log
sqlsrv.sort_order:	${ASE_SORT_ORDER}
sqlsrv.default_characterset:	${ASE_CHARSET}
sqlsrv.default_language:	${ASE_LANGUAGE}
sqlsrv.do_upgrade: no
sqlsrv.sybsystemprocs_device_physical_name: ${ASE_DATA_PATH}/sysprocs.dat
sqlsrv.sybsystemprocs_device_size: 184
sqlsrv.sybsystemprocs_database_size: 184
sqlsrv.sybsystemdb_device_physical_name: ${ASE_DATA_PATH}/sybsysdb.dat
sqlsrv.sybsystemdb_device_size: 24
sqlsrv.sybsystemdb_database_size: 24
sqlsrv.tempdb_device_physical_name: ${ASE_DATA_PATH}/tempdbdev.dat
sqlsrv.tempdb_device_size: 325
sqlsrv.tempdb_database_size: 325
sqlsrv.default_backup_server: ${ASE_DS_NAME}_BS
sqlsrv.do_configure_pci: yes
sqlsrv.sybpcidb_device_physical_name: ${ASE_DATA_PATH}/sybpcidbdev_data.dat
sqlsrv.sybpcidb_device_size: 384
sqlsrv.sybpcidb_database_size: 384
sqlsrv.do_optimize_config: no
sqlsrv.avail_physical_memory:
sqlsrv.avail_cpu_num:
EOF

    # Build ASE server using resource file
    log_info "Building ASE server (srvbuildres)..."
    if ! srvbuildres -r "${SQLBUILD_RES}" 2>&1; then
        log_error "Failed to build ASE server"
        exit 1
    fi

    # srvbuildres leaves the server running; wait for it to be ready
    if ! wait_for_ase "${WAIT_SEC}"; then
        log_error "ASE server failed to start after srvbuildres"
        exit 1
    fi

    # Generate sqllocres resource file
    SQLLOC_RES="$(mktemp /tmp/sqlloc-res.XXXXXX)"
    cat <<EOF > "${SQLLOC_RES}"
sybinit.release_directory: USE_DEFAULT
sqlsrv.server_name: ${ASE_DS_NAME}
sqlsrv.sa_login: sa
sqlsrv.sa_password: ${ASE_SA_PASSWORD}
sqlsrv.default_language: ${ASE_LANGUAGE}
sqlsrv.language_install_list: ${ASE_LANGUAGE_INSTALL_LIST}
sqlsrv.default_characterset: ${ASE_CHARSET}
sqlsrv.characterset_install_list: ${ASE_CHARSET}
sqlsrv.characterset_remove_list: USE_DEFAULT
sqlsrv.sort_order: ${ASE_SORT_ORDER}
EOF

    # Configure locales and character sets
    log_info "Configuring locales and character sets (sqllocres)..."
    if ! sqllocres -r "${SQLLOC_RES}" 2>&1; then
        log_error "Failed to configure locales - continuing anyway"
    fi

    # Disable async I/O for compatibility
    log_info "Disabling async I/O in config..."
    if ! sed -i 's/allow sql server async i\/o = DEFAULT/allow sql server async i\/o = 0/g' "${SYBASE}/${SYBASE_ASE}/${ASE_DS_NAME}.cfg"; then
        log_error "Failed to configure async I/O setting"
        exit 1
    fi

    process_init_files

    # Shutdown server after initial configuration
    log_info "Shutting down server after initial configuration..."
    if ! isql -S "${ASE_DS_NAME}" -Usa -P "${ASE_SA_PASSWORD}" -D "${ASE_DB}" <<SQL
use master
go
shutdown
go
SQL
    then
        log_error "Failed to shutdown server after configuration"
        exit 1
    fi

    log_info "Waiting for server to stop..."
    shutdown_wait=0
    while isql -S "${ASE_DS_NAME}" -Usa -P "${ASE_SA_PASSWORD}" -D "${ASE_DB}" <<-SQL 2>/dev/null
SELECT 1
GO
SQL
    do
        if [ ${shutdown_wait} -ge 30 ]; then
            log_error "Server did not stop within 30s"
            exit 1
        fi
        sleep 2
        shutdown_wait=$((shutdown_wait + 2))
    done
    log_info "Server stopped cleanly"
fi

# Start ASE server (both first-run after setup and subsequent runs)
log_info "Starting ASE server..."
if ! startserver -f "${RUN_FILE}"; then
    log_error "Failed to start ASE server"
    exit 1
fi

# Wait for ASE to be ready
if ! wait_for_ase "${WAIT_SEC}"; then
    log_error "ASE server failed to start within timeout"
    exit 1
fi

log_info "ASE server started successfully on port ${ASE_PORT}"
log_info "Data source name: ${ASE_DS_NAME}"

# Keep container running
tail -f "${SYBASE}/${SYBASE_ASE}/install/${ASE_DS_NAME}.log"
