#!/usr/bin/env bash

source ./SYBASE.sh
set -xuo pipefail
SQL_DIR="${SQL_DIR:-/docker-entrypoint-initdb.d/sql}"

ASE_HOST="${ASE_HOST:-localhost}"
ASE_PORT="${ASE_PORT:-5000}"
ASE_DB="${ASE_DB:-master}"

export ASE_DS_NAME=${ASE_DS_NAME:-MYSYBASE}
# password
export ASE_SA_PASSWORD=${ASE_SA_PASSWORD:-$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 16; echo)}
# path
export ASE_INSTALL_PATH=$SYBASE
export ASE_DATA_PATH=${ASE_DATA_PATH:-${ASE_INSTALL_PATH}/data}


WAIT_SEC="${WAIT_SEC:-60}"

isql_cmd() {
  # -b: エラーで終了コードを返す（環境により未対応の場合あり）
  # -w: 出力幅
  isql --retserverror -S "${ASE_DS_NAME}" -Usa -P "${ASE_SA_PASSWORD}" -D "${ASE_DB}" -w 1000 "$@"
}

if [[ -f $SYBASE/$SYBASE_ASE/install/RUN_${ASE_DS_NAME}  ]] 
then
startserver -f $SYBASE/$SYBASE_ASE/install/RUN_${ASE_DS_NAME}
else
cat <<EOF > /tmp/sap-sqlbuild-res
# --- This file was generated by Sybase Installer ---
#
sybinit.release_directory: ${ASE_INSTALL_PATH}
sybinit.product: sqlsrv
sqlsrv.server_name: ${ASE_DS_NAME}
sqlsrv.sa_password: ${ASE_SA_PASSWORD}
sqlsrv.new_config: yes
sqlsrv.do_add_server: yes
sqlsrv.network_protocol_list: tcp
sqlsrv.network_hostname_list: localhost
sqlsrv.network_port_list: ${ASE_PORT}
sqlsrv.application_type: MIXED
sqlsrv.server_page_size: 16k
sqlsrv.force_buildmaster: no
sqlsrv.addl_cmdline_parameters:
sqlsrv.master_device_physical_name: ${ASE_DATA_PATH}/master.dat
sqlsrv.master_device_size: 384
sqlsrv.master_database_size: 300
sqlsrv.errorlog: ${ASE_INSTALL_PATH}/${SYBASE_ASE}/install/${ASE_DS_NAME}.log
sqlsrv.sort_order:	USE_DEFAULT
sqlsrv.default_characterset:	utf8
sqlsrv.default_language:	japanese
sqlsrv.do_upgrade: no
sqlsrv.sybsystemprocs_device_physical_name: ${ASE_DATA_PATH}/sysprocs.dat
sqlsrv.sybsystemprocs_device_size: 184
sqlsrv.sybsystemprocs_database_size: 184
sqlsrv.sybsystemdb_device_physical_name: ${ASE_DATA_PATH}/sybsysdb.dat
sqlsrv.sybsystemdb_device_size: 24
sqlsrv.sybsystemdb_database_size: 24
sqlsrv.tempdb_device_physical_name: ${ASE_DATA_PATH}/tempdbdev.dat
sqlsrv.tempdb_device_size: 325
sqlsrv.tempdb_database_size: 325
sqlsrv.default_backup_server: ${ASE_DS_NAME}_BS
sqlsrv.do_configure_pci: yes
sqlsrv.sybpcidb_device_physical_name: ${ASE_DATA_PATH}/sybpcidbdev_data.dat
sqlsrv.sybpcidb_device_size: 384
sqlsrv.sybpcidb_database_size: 384
sqlsrv.do_optimize_config: no
sqlsrv.avail_physical_memory:
sqlsrv.avail_cpu_num:
EOF


srvbuildres -r /tmp/sap-sqlbuild-res 2>&1

cat <<EOF > /tmp/sqlloc-res 
sybinit.release_directory: USE_DEFAULT
sqlsrv.server_name: ${ASE_DS_NAME}
sqlsrv.sa_login: sa
sqlsrv.sa_password: ${ASE_SA_PASSWORD}
#sqlsrv.default_language: japanese
sqlsrv.language_install_list: us_english,japanese
#sqlsrv.language_remove_list: spanish
#sqlsrv.default_characterset: utf8
sqlsrv.characterset_install_list: utf8,sjis,eucjis
sqlsrv.characterset_remove_list: USE_DEFAULT
sqlsrv.sort_order: USE_DEFAULT

# An example sqlloc resource file...
# sybinit.release_directory: USE_DEFAULT
# sqlsrv.server_name: PUT_YOUR_SERVER_NAME_HERE
# sqlsrv.sa_login: sa
# sqlsrv.sa_password: 
# sqlsrv.default_language: french
# sqlsrv.language_install_list: spanish,german
# sqlsrv.language_remove_list: USE_DEFAULT
# sqlsrv.default_characterset: cp437
# sqlsrv.characterset_install_list: mac,cp850
# sqlsrv.characterset_remove_list: USE_DEFAULT
# "sqlsrv.sort_order" can be sort order name (dictionary_cp437) or file name (dictionary.srt)
# sqlsrv.sort_order: dictionary_cp437 
EOF
sqllocres -r /tmp/sqlloc-res 2>&1  
sed -i 's/allow sql server async i\/o = DEFAULT/allow sql server async i\/o = 0/g' ${SYBASE}/${SYBASE_ASE}/${ASE_DS_NAME}.cfg


#shutdown
#
isql_cmd <<SQL
use master
go
-- shutdown SYB_BACKUP
-- go
shutdown
go
SQL
fi 


$SYBASE/$SYBASE_ASE/install/RUN_${ASE_DS_NAME}   
