#!/usr/bin/env bash
#
# ASE Docker Entry Point
# Initializes and starts SAP ASE server
#

source ./SYBASE.sh
set -euo pipefail

# SQL initialization directory
SQL_DIR="${SQL_DIR:-/docker-entrypoint-initdb.d/sql}"

# ASE connection configuration
ASE_HOST="${ASE_HOST:-localhost}"
ASE_PORT="${ASE_PORT:-5000}"
ASE_DB="${ASE_DB:-master}"

# Data source name for interfaces file
export ASE_DS_NAME=${ASE_DS_NAME:-MYSYBASE}

# SA password - generate random if not provided
export ASE_SA_PASSWORD=${ASE_SA_PASSWORD:-$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 16; echo)}

# Installation and data paths
export ASE_INSTALL_PATH=$SYBASE
export ASE_DATA_PATH=${ASE_DATA_PATH:-${ASE_INSTALL_PATH}/data}

# Maximum time to wait for ASE startup (seconds)
WAIT_SEC="${WAIT_SEC:-60}"

# ASE configuration: language, charset, sort order
export ASE_LANGUAGE=${ASE_LANGUAGE:-japanese}
export ASE_CHARSET=${ASE_CHARSET:-utf8}
export ASE_SORT=${ASE_SORT:-USE_DEFAULT}

# Logging functions
log_info() {
    echo "[INFO] $*"
}

log_error() {
    echo "[ERROR] $*" >&2
}

# Execute isql command with error handling
isql_cmd() {
    # --retserverror: Return server error codes
    # -b: Exit on error (batch mode)
    # -w: Output width
    isql --retserverror -S "${ASE_DS_NAME}" -Usa -P "${ASE_SA_PASSWORD}" -D "${ASE_DB}" -w 1000 "$@"
}

# Wait for ASE server to be ready
wait_for_ase() {
    local max_wait="${1:-60}"
    local elapsed=0
    local interval=5

    log_info "Waiting for ASE server to be ready (max ${max_wait}s)..."

    while [ ${elapsed} -lt ${max_wait} ]; do
        if pgrep -x dataserver >/dev/null 2>&1; then
            # Try to connect using isql
            if isql_cmd <<-SQL 2>/dev/null
SELECT @@VERSION
GO
EXIT
SQL
            then
                log_info "ASE server is ready and accepting connections"
                return 0
            fi
        fi

        log_info "Waiting for ASE... (${elapsed}s/${max_wait}s)"
        sleep ${interval}
        elapsed=$((elapsed + interval))
    done

    log_error "ASE server did not become ready within ${max_wait}s"
    return 1
}

# Check if ASE is already configured
if [[ -f $SYBASE/$SYBASE_ASE/install/RUN_${ASE_DS_NAME} ]]; then
    log_info "ASE already configured, starting existing server..."
    if ! startserver -f $SYBASE/$SYBASE_ASE/install/RUN_${ASE_DS_NAME}; then
        log_error "Failed to start ASE server"
        exit 1
    fi
 else
    log_info "ASE not configured, performing initial setup..."
    # Security: Set restrictive umask for temp files
    umask 077
    SQLBUILD_RES="$(mktemp /tmp/sap-sqlbuild-res.XXXXXX)"
    trap 'rm -f "${SQLBUILD_RES}"' EXIT
cat <<EOF > "${SQLBUILD_RES}"
# --- This file was generated by Sybase Installer ---
#
sybinit.release_directory: ${ASE_INSTALL_PATH}
sybinit.product: sqlsrv
sqlsrv.server_name: ${ASE_DS_NAME}
sqlsrv.sa_password: ${ASE_SA_PASSWORD}
sqlsrv.new_config: yes
sqlsrv.do_add_server: yes
sqlsrv.network_protocol_list: tcp
sqlsrv.network_hostname_list: localhost
sqlsrv.network_port_list: ${ASE_PORT}
sqlsrv.application_type: MIXED
sqlsrv.server_page_size: 16k
sqlsrv.force_buildmaster: no
sqlsrv.addl_cmdline_parameters:
sqlsrv.master_device_physical_name: ${ASE_DATA_PATH}/master.dat
sqlsrv.master_device_size: 384
sqlsrv.master_database_size: 300
sqlsrv.errorlog: ${ASE_INSTALL_PATH}/${SYBASE_ASE}/install/${ASE_DS_NAME}.log
sqlsrv.sort_order:	${ASE_SORT}
sqlsrv.default_characterset:	${ASE_CHARSET}
sqlsrv.default_language:	${ASE_LANGUAGE}
sqlsrv.do_upgrade: no
sqlsrv.sybsystemprocs_device_physical_name: ${ASE_DATA_PATH}/sysprocs.dat
sqlsrv.sybsystemprocs_device_size: 184
sqlsrv.sybsystemprocs_database_size: 184
sqlsrv.sybsystemdb_device_physical_name: ${ASE_DATA_PATH}/sybsysdb.dat
sqlsrv.sybsystemdb_device_size: 24
sqlsrv.sybsystemdb_database_size: 24
sqlsrv.tempdb_device_physical_name: ${ASE_DATA_PATH}/tempdbdev.dat
sqlsrv.tempdb_device_size: 325
sqlsrv.tempdb_database_size: 325
sqlsrv.default_backup_server: ${ASE_DS_NAME}_BS
sqlsrv.do_configure_pci: yes
sqlsrv.sybpcidb_device_physical_name: ${ASE_DATA_PATH}/sybpcidbdev_data.dat
sqlsrv.sybpcidb_device_size: 384
sqlsrv.sybpcidb_database_size: 384
sqlsrv.do_optimize_config: no
sqlsrv.avail_physical_memory:
sqlsrv.avail_cpu_num:
EOF


# Build ASE server using resource file
if ! srvbuildres -r "${SQLBUILD_RES}" 2>&1; then
    log_error "Failed to build ASE server"
    exit 1
fi

SQLLOC_RES="$(mktemp /tmp/sqlloc-res.XXXXXX)"
trap 'rm -f "${SQLLOC_RES}"' EXIT
cat <<EOF > "${SQLLOC_RES}"
sybinit.release_directory: USE_DEFAULT
sqlsrv.server_name: ${ASE_DS_NAME}
sqlsrv.sa_login: sa
sqlsrv.sa_password: ${ASE_SA_PASSWORD}
sqlsrv.default_language: ${ASE_LANGUAGE}
sqlsrv.language_install_list: us_english,${ASE_LANGUAGE}
#sqlsrv.language_remove_list: spanish
sqlsrv.default_characterset: ${ASE_CHARSET}
sqlsrv.characterset_install_list: ${ASE_CHARSET},sjis,eucjis
sqlsrv.characterset_remove_list: USE_DEFAULT
sqlsrv.sort_order: ${ASE_SORT}

# An example sqlloc resource file...
# sybinit.release_directory: USE_DEFAULT
# sqlsrv.server_name: PUT_YOUR_SERVER_NAME_HERE
# sqlsrv.sa_login: sa
# sqlsrv.sa_password:
# sqlsrv.default_language: french
# sqlsrv.language_install_list: spanish,german
# sqlsrv.language_remove_list: USE_DEFAULT
# sqlsrv.default_characterset: cp437
# sqlsrv.characterset_install_list: mac,cp850
# sqlsrv.characterset_remove_list: USE_DEFAULT
# "sqlsrv.sort_order" can be sort order name (dictionary_cp437) or file name (dictionary.srt)
# sqlsrv.sort_order: dictionary_cp437
EOF
# Configure locales and character sets
if ! sqllocres -r "${SQLLOC_RES}" 2>&1; then
    log_error "Failed to configure locales"
    exit 1
fi

# Disable async I/O for compatibility
if ! sed -i 's/allow sql server async i\/o = DEFAULT/allow sql server async i\/o = 0/g' ${SYBASE}/${SYBASE_ASE}/${ASE_DS_NAME}.cfg; then
    log_error "Failed to configure async I/O setting"
    exit 1
fi


    # Shutdown server after initial configuration
    log_info "Shutting down server after initial configuration..."
    if ! isql_cmd <<SQL
use master
go
shutdown
go
SQL
    then
        log_error "Failed to shutdown server after configuration"
        exit 1
    fi
fi

# Start ASE server
log_info "Starting ASE server..."
if ! $SYBASE/$SYBASE_ASE/install/RUN_${ASE_DS_NAME}; then
    log_error "Failed to start ASE server"
    exit 1
fi

# Wait for ASE to be ready
if ! wait_for_ase "${WAIT_SEC}"; then
    log_error "ASE server failed to start within timeout"
    exit 1
fi

log_info "ASE server started successfully on port ${ASE_PORT}"
log_info "Data source name: ${ASE_DS_NAME}"

# Keep container running
tail -f ${SYBASE}/${SYBASE_ASE}/install/${ASE_DS_NAME}.log   
